name: Node.js CI

on:
  pull_request:
  workflow_dispatch:

permissions: write-all

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2.3.1
